definitions:
  models.Post:
    properties:
      body:
        type: string
      id:
        type: integer
      title:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        items:
          type: integer
        type: array
      phoneNumber:
        type: string
      posts:
        items:
          $ref: '#/definitions/models.Post'
        type: array
      surname:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server server.
  title: Fiber Swagger Example API
  version: "2.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      summary: Show a models.Post
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      summary: Show a models.Post
swagger: "2.0"
